// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnG6dOyWwwqWkzfrGKHfYJBu2RK3rt6Qc',
    appId: '1:412038702642:web:5f151cd2625c8c06607e2b',
    messagingSenderId: '412038702642',
    projectId: 'amaudo-healthcare',
    authDomain: 'amaudo-healthcare.firebaseapp.com',
    storageBucket: 'amaudo-healthcare.firebasestorage.app',
    measurementId: 'G-3RL9F48ZJM',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7JUH6qhrnF3HkswipkJhQIdLpTYhtgi4',
    appId: '1:412038702642:android:17be00049becea9c607e2b',
    messagingSenderId: '412038702642',
    projectId: 'amaudo-healthcare',
    storageBucket: 'amaudo-healthcare.firebasestorage.app',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSIwSqOaYGWhjp56Q7vz8K-CCU4lFDJx8',
    appId: '1:412038702642:ios:a37885743bd7ae14607e2b',
    messagingSenderId: '412038702642',
    projectId: 'amaudo-healthcare',
    storageBucket: 'amaudo-healthcare.firebasestorage.app',
    androidClientId: '412038702642-20ett3bqloitbo9ll8p1fmm9r6k54uij.apps.googleusercontent.com',
    iosClientId: '412038702642-t9m8qqjgkhsmej4s4a3lgkt05f75c1gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.amaudoManagementApp',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSIwSqOaYGWhjp56Q7vz8K-CCU4lFDJx8',
    appId: '1:412038702642:ios:a37885743bd7ae14607e2b',
    messagingSenderId: '412038702642',
    projectId: 'amaudo-healthcare',
    storageBucket: 'amaudo-healthcare.firebasestorage.app',
    androidClientId: '412038702642-20ett3bqloitbo9ll8p1fmm9r6k54uij.apps.googleusercontent.com',
    iosClientId: '412038702642-t9m8qqjgkhsmej4s4a3lgkt05f75c1gv.apps.googleusercontent.com',
    iosBundleId: 'com.example.amaudoManagementApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAnG6dOyWwwqWkzfrGKHfYJBu2RK3rt6Qc',
    appId: '1:412038702642:web:b8a13ba7e8313b3c607e2b',
    messagingSenderId: '412038702642',
    projectId: 'amaudo-healthcare',
    authDomain: 'amaudo-healthcare.firebaseapp.com',
    storageBucket: 'amaudo-healthcare.firebasestorage.app',
    measurementId: 'G-XK8TW4SPJS',
  );
}
